[tool.poetry]
name = "pttautosign"
version = "0.1.1"
description = ""
authors = ["tasi788 <tdc@tdccc.com.tw>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
PyPtt = "^1.6.0"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
