name: Daily Trigger

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 簽出原始碼
        uses: actions/checkout@v4

      - name: 設定 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安裝基礎套件
        run: pip install requests

      - name: 執行自動登入
        env:
          bot_token: ${{ secrets.BOT_TOKEN }}
          chat_id: ${{ secrets.CHAT_ID }}
          ptt_id_1: ${{ secrets.PTT_ID_1 }}
        run: python main.py
